# src/models/read_file_plan.py
"""
Defines the Pydantic model for planning a file read action.
"""

from pydantic import BaseModel, Field
from typing import Literal

class ReadFilePlan(BaseModel):
    """
    Plan generated by the Planner to instruct the Executor to read a file's content.
    """
    action: Literal["read_file"] = Field(..., description="Specifies the action to read a file.")
    file_path: str = Field(..., description="The path to the file that needs to be read.")
